import {readFileSync} from 'node:fs';
import assert from 'node:assert/strict';
const source=readFileSync(new URL('../src/web/files.js',import.meta.url));
const {relativePath,selectedFiles,droppedFiles,folderBatches}=await import(`data:text/javascript;base64,${source.toString('base64')}`);
const file=(name,path='')=>({name,webkitRelativePath:path});
assert.equal(selectedFiles([file('中文.txt')])[0].path,'中文.txt');
assert.equal(selectedFiles([file('同名.txt','目录/甲/同名.txt')],true)[0].path,'目录/甲/同名.txt');
assert.equal(relativePath('目录\\子目录\\说明.txt'),'目录/子目录/说明.txt');
for(const invalid of ['../x','a/../x','/root','C:\\file','a//b','a/./b',''])assert.throws(()=>relativePath(invalid));
assert.throws(()=>selectedFiles([file('flat.txt')],true),/未返回文件夹层级/);
const leaf=name=>({name,isFile:true,file(resolve){resolve(file(name));}});
function directory(name,children) {
  return {name,isDirectory:true,createReader(){let offset=0;return {readEntries(resolve){const batch=children.slice(offset,offset+100);offset+=100;resolve(batch);}};}};
}
const root=directory('项目',[directory('甲',[leaf('同名.txt')]),directory('乙',[leaf('同名.txt')]),...Array.from({length:203},(_,i)=>leaf(i+'.txt'))]);
const result=await droppedFiles({items:[{kind:'file',webkitGetAsEntry:()=>root}],files:[]});
assert.equal(result.length,205);
assert.equal(result[0].path,'项目/甲/同名.txt');
assert.equal(result[1].path,'项目/乙/同名.txt');
assert.equal(result.at(-1).path,'项目/202.txt');
assert.equal((await droppedFiles({items:[],files:[file('fallback.txt')]}))[0].path,'fallback.txt');
assert.deepEqual(await droppedFiles({items:[{kind:'file',webkitGetAsEntry:()=>directory('空',[])}],files:[]}),[]);
await assert.rejects(()=>droppedFiles({items:[{kind:'file',webkitGetAsEntry:()=>root},{kind:'file'}],files:[]}),/部分拖放项目/);
await assert.rejects(()=>droppedFiles({items:[{kind:'file',webkitGetAsEntry:()=>({name:'失败',isFile:true,file(resolve,reject){reject(new Error('denied'));}})}],files:[]}),/denied/);
console.log('PASS relative paths, unsafe paths, directory selection, recursive drop, >100-entry batches, same-name children and read failures');
let counter=0;
const grouped=folderBatches([{file:{size:3},path:'目录/甲/a.txt'},{file:{size:5},path:'目录/乙/b.txt'},{file:{size:2},path:'另一目录/c.txt'},{file:{size:1},path:'单文件.txt'}],()=>String(++counter));
assert.equal(grouped[0].batch,grouped[1].batch);
assert.equal(grouped[0].batch.count,2);assert.equal(grouped[0].batch.total,8);
assert.notEqual(grouped[0].batch.id,grouped[2].batch.id);
assert.equal(grouped[3].batch,undefined);
assert.throws(()=>folderBatches([{file:{size:1},path:'目录/a'},{file:{size:1},path:'目录/a'}],()=>''),/重复路径/);
console.log('PASS folder-scoped batch identity, count, bytes and duplicate-path rejection');
const {batchPlan,limitValue}=await import(`data:text/javascript;base64,${source.toString('base64')}`);
const many=Array.from({length:6001},(_,i)=>({path:`large/${i}.txt`,file:{size:i%7}}));
let sequence=0;const makeId=()=>String(++sequence);
const plan=batchPlan(many,makeId);
assert.equal(plan.entries.length,6001);assert.equal(plan.items.length,1);assert.equal(plan.items[0].count,'6001');
assert.equal(plan.items[0].total,String(many.reduce((total,item)=>total+item.file.size,0)));
assert(plan.entries.every(entry=>entry.item===0),'folder is a single consent item');
const loose=batchPlan(Array.from({length:50},(_,i)=>({path:`${i}.txt`,file:{size:2}})),makeId);
assert.equal(loose.items.length,50);assert.equal(loose.total,'100');
assert.throws(()=>batchPlan(many,makeId,'5000','0'),/上限/);
assert.throws(()=>batchPlan([{path:'a',file:{size:6}},{path:'b',file:{size:6}}],makeId,'0','10'),/上限/);
const precise=batchPlan([{path:'root/a',file:{size:Number.MAX_SAFE_INTEGER}},{path:'root/b',file:{size:2}}],makeId);
assert.equal(precise.items[0].total,'9007199254740993','batch total remains precise above JS safe integer');
assert.equal(limitValue('0',1048576n),'0');assert.equal(limitValue('10',1048576n),'10485760');
assert.throws(()=>limitValue('-1'));assert.throws(()=>limitValue('1.5'));assert.throws(()=>limitValue('18446744073709551616'));
console.log('PASS default unlimited 6001-file manifest, 50 selectable files, exact totals and configurable limits');
